- app/services/EstimatedTaxLiabilityService.scala
- project/MicroService.scala
- test/services/EstimatedTaxLiabilityServiceSpec.scala
- test/services/MockFinancialDataConnector.scala
Also snuck in a correction to the scoverage settings
> [BTAT-11] Created the service to retrieve the EstimatedTaxLiability

- app/config/MicroserviceAppConfig.scala
- app/connectors/FinancialDataConnector.scala
- conf/application.conf
- it/helpers/servicemocks/FinancialDataStub.scala
Reverts hmrc/income-tax-view-change#15
> Revert "[BTAT-246-Stub-Context] add itvc stub context route to config"

- app/connectors/GetBusinessDetailsConnector.scala
- app/controllers/GetBusinessDetailsController.scala
- app/models/incomeSourceDetails/IncomeSourceDetailsResponseModel.scala
- app/services/GetBusinessDetailsService.scala
- conf/app.routes
- it/assets/BaseIntegrationTestConstants.scala
- it/assets/BusinessDetailsIntegrationTestConstants.scala
- it/assets/IncomeSourceIntegrationTestConstants.scala
- it/controllers/GetBusinessDetailsControllerISpec.scala
- it/helpers/ComponentSpecBase.scala
- it/helpers/servicemocks/DesBusinessDetailsCallWithNinoStub.scala
- test/assets/IncomeSourceDetailsTestConstants.scala
- test/connectors/GetBusinessDetailsConnectorSpec.scala
- test/controllers/GetBusinessDetailsControllerSpec.scala
- test/mocks/MockGetBusinessDetailsConnector.scala
- test/mocks/MockGetBusinessDetailsService.scala
- test/services/GetBusinessDetailsServiceSpec.scala
> MISUV-1438: call using nino to get business details

- app/connectors/FinancialDetailsConnector.scala
- app/connectors/httpParsers/ChargeHttpParser.scala
- app/models/financialDetails/DocumentDetail.scala
- it/assets/OutStandingChargesIntegrationTestConstant.scala
- it/controllers/FinancialDetailChargesControllerISpec.scala
- it/controllers/OutStandingChargesControllerISpec.scala
- it/helpers/servicemocks/DesChargesStub.scala
- test/assets/FinancialDataTestConstants.scala
- test/connectors/FinancialDetailsConnectorSpec.scala
- test/connectors/httpParsers/ChargesHttpParserSpec.scala
- test/models/financialDetails/DocumentDetailSpec.scala
Added 5 new fields to pass from API to the frontend:
- interestRate
- interestFromDate
- interestEndDate
- latePaymentInterestAmount
- interestOutstandingAmount
> MISUV-827: New fields for Accruing Interest in Charge API response

- build.sbt
Excluded testOnlyDoNotUseInAppConf
> MISUV-3752 : Exclusion filters

- app/controllers/UpdateIncomeSourceController.scala
- app/models/updateIncomeSource/request/UpdateIncomeSourceRequestModel.scala
- conf/app.routes
- it/assets/UpdateIncomeSourceIntegrationTestConstants.scala
- it/controllers/UpdateIncomeSourceControllerISpec.scala
- it/helpers/ComponentSpecBase.scala
- it/helpers/servicemocks/IfUpdateIncomeSourceStub.scala
- test/assets/UpdateIncomeSourceTestConstants.scala
- test/controllers/UpdateIncomeSourceControllerSpec.scala
> MISUV-5766 api1776 update

- app/connectors/FinancialDetailsConnector.scala
> MISUV-6494: Add extra logging when extract FinancialDetails

- app/connectors/FinancialDetailsConnector.scala
> MISUV-www:

- app/connectors/CreateBusinessDetailsConnector.scala
> MISUV-6581 - TxM event -Create Income Source: success/failure (API#1566)

- app/connectors/FinancialDetailsConnector.scala
- it/helpers/servicemocks/DesChargesStub.scala
- test/connectors/FinancialDetailsConnectorSpec.scala
This reverts commit a4c957d4d900935e3524abd81a6d2274296e5f70.
> Revert "MISUV-6684: temp change 1553 single query param (#245)"

- app/connectors/ReportDeadlinesConnector.scala
> MISUV-6666: change log level

- app/connectors/GetBusinessDetailsConnector.scala
- app/connectors/ITSAStatusConnector.scala
- app/connectors/IncomeSourceDetailsConnector.scala
- app/connectors/ReportDeadlinesConnector.scala
- app/connectors/UpdateIncomeSourceConnector.scala
- app/connectors/httpParsers/CalculationListHttpParser.scala
- app/connectors/httpParsers/ChargeHistoryHttpParser.scala
- app/connectors/httpParsers/ChargeHttpParser.scala
- app/connectors/httpParsers/OutStandingChargesHttpParser.scala
- app/connectors/httpParsers/PaymentAllocationsHttpParser.scala
- app/connectors/httpParsers/RepaymentHistoryHttpParser.scala
- app/controllers/CalculationListController.scala
- app/controllers/ITSAStatusController.scala
- app/controllers/ReportDeadlinesController.scala
- app/controllers/UpdateIncomeSourceController.scala
- app/services/IncomeSourceDetailsService.scala
* apply next Scala Fix rules in BE project:
-    DisableSyntax,
-   RemoveUnused,
-   RedundantSyntax,
-   ProcedureSyntax,
-   LeakingImplicitClassVal,
-   NoAutoTupling
> MISUV-6898: code tidy up BE

- app/controllers/CreateBusinessDetailsController.scala
- app/controllers/GetBusinessDetailsController.scala
- app/controllers/IncomeSourceDetailsController.scala
- app/controllers/ReportDeadlinesController.scala
- app/controllers/predicates/AuthenticationPredicate.scala
- app/services/IncomeSourceDetailsService.scala
- build.sbt
- conf/application.conf
- conf/prod.routes
- project/build.properties
- project/plugins.sbt
- test/models/financialDetails/responses/ChargesResponseSpec.scala
- test/utils/MaterializerSupport.scala
- test/utils/TestSupport.scala
* - migration changes as per migration instruction;
> MISUV-6797: BE migration to Play 3.0

- app/models/repaymentHistory/RepaymentHistory.scala
- it/test/controllers/RepaymentHistoryControllerISpec.scala
- test/assets/RepaymentHistoryTestConstants.scala
- test/connectors/httpParsers/RepaymentHistoryHttpParserSpec.scala
- test/models/repaymentHistory/RepaymentHistorySpec.scala
MISUV-7206: Added RepaymentHistoryStatus
> MISUV-7081: Refunds having status of 'Approved' to be displayed on history page

- app/models/financialDetails/DocumentDetail.scala
- it/test/assets/FinancialDetailIntegrationTestConstants.scala
- test/assets/FinancialDataTestConstants.scala
- test/models/financialDetails/DocumentDetailSpec.scala
- test/models/financialDetails/responses/ChargesResponseSpec.scala
poaRelevantAmount field added in DocumentDetail case class and refactor tests
> MISUV-7482_BE: poaRelevantAmount field added

- app/connectors/CalculationListConnector.scala
- app/connectors/CreateBusinessDetailsConnector.scala
- app/connectors/FinancialDetailsConnector.scala
- app/connectors/GetBusinessDetailsConnector.scala
- app/connectors/RepaymentHistoryDetailsConnector.scala
- app/connectors/ReportDeadlinesConnector.scala
- app/connectors/UpdateIncomeSourceConnector.scala
- app/connectors/httpParsers/CalculationListHttpParser.scala
- app/connectors/httpParsers/ChargeHistoryHttpParser.scala
- app/connectors/httpParsers/ChargeHttpParser.scala
- app/connectors/httpParsers/OutStandingChargesHttpParser.scala
- app/connectors/httpParsers/PaymentAllocationsHttpParser.scala
- app/connectors/httpParsers/RepaymentHistoryHttpParser.scala
- app/connectors/httpParsers/ResponseHttpParsers.scala
- app/connectors/itsastatus/ITSAStatusConnector.scala
- app/controllers/CalculationListController.scala
- app/controllers/CreateBusinessDetailsController.scala
- app/controllers/FinancialDetailChargesController.scala
- app/controllers/GetBusinessDetailsController.scala
- app/controllers/ITSAStatusController.scala
- app/controllers/IncomeSourceDetailsController.scala
- app/controllers/ReportDeadlinesController.scala
- app/controllers/UpdateIncomeSourceController.scala
- app/controllers/predicates/AuthenticationPredicate.scala
- app/models/financialDetails/SubItem.scala
- app/services/CalculationListService.scala
- app/services/GetBusinessDetailsService.scala
- app/services/IncomeSourceDetailsService.scala
- conf/logback-test.xml
- conf/logback.xml
remove [class][method] names from log statements
> remove [class][method] names from log statements

- app/models/reportDeadlines/ReportDeadlineModel.scala
- it/test/assets/ReportDeadlinesIntegrationTestConstants.scala
- it/test/controllers/ReportDeadlinesControllerISpec.scala
- it/test/helpers/servicemocks/DesReportDeadlinesStub.scala
- test/assets/ReportDeadlinesTestConstants.scala
- test/models/reportDeadlines/ReportDeadlineModelSpec.scala
> MISUV-7864-include-status

- app/connectors/itsastatus/OptOutUpdateRequestModel.scala
- app/models/reportDeadlines/ReportDeadlineModel.scala
> MISUV-7936-reason-as-string

- app/models/reportDeadlines/ReportDeadlineModel.scala
- test/connectors/itsastatus/OptOutUpdateRequestModelSpec.scala
> MISUV-7940-model-unit-tests

- build.sbt
* re-enabled scover min level for the project in build.sbt;
> MISUV-8753:

- app/connectors/hip/FinancialDetailsHipConnector.scala
- app/connectors/hip/HipConnectorDataHelper.scala
** drop not used code and re-wire X-Receipt-Date;
> MISUV-9518_Hip: re-use existing data/time formatting from ~Utils

- app/connectors/hip/HipConnectorDataHelper.scala
** reverse X-Originating-System change
> MISUV-9518_Hip:

- app/connectors/hip/httpParsers/ChargeHipHttpParser.scala
** add extra logging before json validation ::HttpStatus::OK;
> MISUV-9518_Hip: extra logging

- app/models/financialDetails/hip/ChargesHipResponse.scala
- it/test/constants/FinancialDetailHipIntegrationTestConstants.scala
** fix financialDetailsItem mapping;
> MISUV-9518_Hip: fix mapping

- app/models/financialDetails/hip/CodingDetailsHip.scala
- app/models/financialDetails/hip/SubItemHip.scala
- it/test/connectors/hip/FinancialDetailsHipConnectorISpec.scala
- it/test/constants/FinancialDetailHipIntegrationTestConstants.scala
- it/test/helpers/FinancialDetailsHipItDataHelper.scala
- test/services/FinancialDetailServiceSpec.scala
** add more tests coverage;
** fix ~SubItem mapping;
> MISUV-9518_Hip: fix ~SubItem mapping
